#!/usr/bin/env tsx
/**
 * Compiles the host-independent rules of redirects.config.json into public/_redirects, the file
 * Cloudflare Workers Static Assets uses to answer redirects before any asset or Worker code runs.
 *
 * Host-scoped rules are intentionally skipped: _redirects cannot match on hostname, so they are
 * handled by the Worker in workers/legacy-redirects.
 *
 * Usage:
 *   npm run cf:redirects           # write public/_redirects
 *   npm run cf:redirects:check     # fail if the file is out of date
 */
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { createMatcher, type RedirectRule } from '../workers/legacy-redirects/src/match';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const CONFIG_PATH = join(ROOT, 'redirects.config.json');
const OUTPUT_PATH = join(ROOT, 'public', '_redirects');

/**
 * Cloudflare reads at most 2,000 exact-path rules and 100 pattern rules, and once the first pattern
 * rule appears every following rule counts against the 100 budget — the remainder is dropped with
 * only a build warning. Emitting the exact-path rules first keeps the whole table in effect.
 */
const MAX_STATIC_RULES = 2000;
const MAX_DYNAMIC_RULES = 100;

const isDynamic = (from: string) => from.includes('*') || from.includes(':');

/** Only host-independent rules reach the matcher below, so any hostname produces the same answer. */
const APEX_HOST = 'insbs.net';

function renderRule({ from, to, status }: RedirectRule) {
  if (!from.startsWith('/')) throw new Error(`Rule source must start with "/": ${from}`);
  if (/\s/.test(from) || /\s/.test(to)) throw new Error(`Rule contains whitespace: ${from} ${to}`);
  return `${from} ${to} ${status}`;
}

/**
 * Hoisting the exact-path rules is only safe while none of them is shadowed by a pattern rule that
 * used to be evaluated first — otherwise the hoisted rule would start answering a path that the
 * pattern rule owns today.
 */
function assertHoistingIsSafe(rules: RedirectRule[]) {
  const patterns = rules
    .map((rule, index) => ({ rule, index }))
    .filter(({ rule }) => isDynamic(rule.from));

  for (const [index, rule] of rules.entries()) {
    if (isDynamic(rule.from)) continue;
    const shadow = patterns.find(
      (candidate) => candidate.index < index && createMatcher([candidate.rule])(APEX_HOST, rule.from)
    );
    if (shadow) {
      throw new Error(
        `"${rule.from}" is already handled by the earlier pattern rule "${shadow.rule.from}", so it ` +
          'cannot be hoisted above it. Remove the unreachable rule or drop the pattern rule.'
      );
    }
  }
}

async function main() {
  const check = process.argv.includes('--check');
  const { rules } = JSON.parse(await readFile(CONFIG_PATH, 'utf-8')) as { rules: RedirectRule[] };
  const pathRules = rules.filter((rule) => !rule.host);

  assertHoistingIsSafe(pathRules);

  const staticRules = pathRules.filter((rule) => !isDynamic(rule.from));
  const dynamicRules = pathRules.filter((rule) => isDynamic(rule.from));
  if (dynamicRules.length > MAX_DYNAMIC_RULES) {
    throw new Error(
      `${dynamicRules.length} pattern rules exceeds the Cloudflare limit of ${MAX_DYNAMIC_RULES}`
    );
  }
  if (staticRules.length > MAX_STATIC_RULES) {
    throw new Error(
      `${staticRules.length} exact-path rules exceeds the Cloudflare limit of ${MAX_STATIC_RULES}`
    );
  }

  const content = [
    '# Generated by scripts/generate-cloudflare-redirects.ts — do not edit by hand.',
    '# Edit redirects.config.json instead, then run `npm run cf:redirects`.',
    ...staticRules.map(renderRule),
    ...dynamicRules.map(renderRule),
    ''
  ].join('\n');

  const current = await readFile(OUTPUT_PATH, 'utf-8').catch(() => null);
  if (check) {
    if (current !== content) {
      throw new Error('public/_redirects is out of date — run `npm run cf:redirects`');
    }
    console.log(`public/_redirects is up to date (${pathRules.length} rules).`);
    return;
  }

  if (current !== content) await writeFile(OUTPUT_PATH, content, 'utf-8');
  console.log(
    `Wrote public/_redirects: ${pathRules.length} rules ` +
      `(${staticRules.length} exact-path, ${dynamicRules.length} pattern).`
  );
}

main().catch((error: Error) => {
  console.error(`[generate-cloudflare-redirects] ${error.message}`);
  process.exit(1);
});
